application: pref-service-dev
version:  pydefault
runtime: python27
api_version: 1
threadsafe: no
module: default

builtins:
  - remote_api: on

# index files
handlers:
- url: /_queue/async.*
  script: furious.handlers.webapp.app
  login: admin

- url: .*
  script: main.app